# Generated by Django 4.0.5 on 2022-09-08 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-date'], 'verbose_name': 'Answer', 'verbose_name_plural': 'Answers'},
        ),
    ]
