# Generated by Django 4.0.5 on 2023-01-26 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_alter_answer_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='device_id',
            new_name='user_id',
        ),
    ]
