# Containers that are needed to execute tests
services:
  tracking-service-backend:
    container_name: tracking-service-backend
    build: .
    env_file:
      - test.env
    tty: true
    restart: unless-stopped

volumes:
  pg_data:
  pg_conf:
  pg_log:
