# Generated by Django 4.2.13 on 2024-05-13 07:35

from django.db import migrations, models
import tracks.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('session_id', models.CharField(default='unknown', max_length=255, primary_key=True, serialize=False)),
                ('start_time', models.BigIntegerField()),
                ('end_time', models.BigIntegerField(blank=True, null=True)),
                ('debug', models.BooleanField(default=False)),
                ('backend', models.CharField(default='unknown', max_length=255)),
                ('positioning_mode', models.CharField(default='unknown', max_length=255)),
                ('user_id', models.CharField(default='unknown', max_length=255)),
                ('device_type', models.CharField(default='unknown', max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('bike_type', models.CharField(default='unknown', max_length=255)),
                ('preference_type', models.CharField(default='unknown', max_length=255)),
                ('activity_type', models.CharField(default='unknown', max_length=255)),
                ('has_battery_data', models.BooleanField(blank=True, null=True)),
                ('avg_battery_consumption', models.FloatField(blank=True, null=True)),
                ('metadata', tracks.fields.JSONField()),
                ('gps_csv', models.TextField(blank=True, null=True)),
                ('accelerometer_csv', models.TextField(blank=True, null=True)),
                ('gyroscope_csv', models.TextField(blank=True, null=True)),
                ('magnetometer_csv', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
