# Generated by Django 4.0.5 on 2022-09-22 07:57

from django.db import migrations, models
import tracks.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw', tracks.fields.JSONField()),
                ('start_time', models.BigIntegerField()),
                ('end_time', models.BigIntegerField()),
                ('debug', models.BooleanField(default=False)),
                ('backend', models.CharField(default='unknown', max_length=255)),
                ('positioning_mode', models.CharField(default='unknown', max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
