# Generated by Django 4.0.5 on 2022-09-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='device_id',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='track',
            name='device_type',
            field=models.CharField(default='unknown', max_length=255),
        ),
    ]
