# Generated by Django 4.0.5 on 2023-01-26 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_track_device_id_track_device_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='device_id',
            new_name='user_id',
        ),
    ]
