# Generated by Django 4.0.5 on 2023-01-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_rename_device_id_track_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='session_id',
            field=models.CharField(default='unknown', max_length=255),
        ),
    ]
