# Generated by Django 4.1.5 on 2023-02-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0004_track_session_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='raw',
            new_name='metadata',
        ),
        migrations.AddField(
            model_name='track',
            name='accelerometer_csv',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='gps_csv',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='gyroscope_csv',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='magnetometer_csv',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='end_time',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
