# Generated by Django 4.1.7 on 2023-02-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0005_rename_raw_track_metadata_track_accelerometer_csv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='activity_type',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='track',
            name='bike_type',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='track',
            name='preference_type',
            field=models.CharField(default='unknown', max_length=255),
        ),
    ]
