# Generated by Django 4.2.11 on 2024-04-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0006_track_activity_type_track_bike_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='avg_battery_consumption',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='can_battery_analysis',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
