# Generated by Django 4.2.11 on 2024-04-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0007_track_avg_battery_consumption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='can_battery_analysis',
        ),
        migrations.AddField(
            model_name='track',
            name='has_battery_data',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
